version: 2.1

            
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: java --version
      - restore_cache:
          keys: [mvn-dependencies_v1]
      - run: ./mvnw install
      - save_cache:
          paths: [~/.m2]
          key: mvn-dependencies_v1
          
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys: [mvn-dependencies_v1]
      - run: java --version
      - run: ./mvnw test

  generate-docker-image-v2:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys: [mvn-dependencies_v1]
      - run:
          name: Build application Docker image
          command: |
            docker version
            
            
  generate-docker-image:
    docker:
        - image: cimg/openjdk:17.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Verify docker is working
          command: |
            docker version
      - restore_cache:
          keys: [mvn-dependencies_v1]
      - run: ./mvnw spring-boot:build-image
      - run: docker images
      - run: |
            echo '$DOCKERHUB_PASS' | docker login -u '$DOCKERHUB_USER' --password-stdin
      - run: docker push spring-petclinic:latest
 
workflows:
  default:
    jobs:
      # - build
      # - test:
         # requires: [build]
      - generate-docker-image
         # requires: [test]