version: 2.1

            
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: java --version
      - restore_cache:
          keys: [mvn-dependencies_v1]
      - run: ./mvnw install
      - save_cache:
          paths: [~/.m2]
          key: mvn-dependencies_v1
          
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys: [mvn-dependencies_v1]
      - run: java --version
      - run: ./mvnw test

  generate-docker-image:
    docker:
      - image: openjdk:17
    steps:
      - checkout
      - restore_cache:
          keys: [mvn-dependencies_v1]
      - run:
            name: install docker
            command: |
                apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common && \
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
                add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
                apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io && \
                rm -rf /var/lib/apt/lists/*
                sudo docker run hello-world
                
                
      - run: ./mvnw spring-boot:build-image
      

workflows:
  default:
    jobs:
      # - build
      # - test:
         # requires: [build]
      - generate-docker-image
         # requires: [test]